apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      primitive: worker
  template:
    metadata:
      labels:
        primitive: worker
    spec:
      containers:
        - name: worker
          image: jorakhachatryan/multi-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
